# Generated by Django 5.1.1 on 2024-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
